POST http://localhost:9000/v1/user/register
Content-Type: application/json

{
  "fullName": "xiao123",
  "bio": "xxXXX",
  "website": "google",
  "username": "fucker",
  "email": "kaiwenxiao0@gmail.com",
  "password": "247955430aA!",
  "uuid": "haha"
}